# GitHub Actions Configuration for Election Modeling Pipeline
# Simplified CI/CD focused on data preparation validation

# Workflow Configuration  
workflows:
  pr_validation:
    description: "Fast PR validation focused on data preparation"
    triggers:
      - "pull_request events"
    timeout_minutes: 15
    focus:
      - "Data loading validation"
      - "Interface compatibility" 
      - "Basic integration tests"
      - "Coalition structure validation"
  
  regression_testing:
    description: "Lightweight regression testing on main branch"
    triggers:
      - "push to main"
      - "manual dispatch"
    timeout_minutes: 15
    focus:
      - "Data preparation regression"
      - "Interface validation"
      - "Basic system health checks"

# Test Configuration
testing:
  validation_focus:
    - "Data loading and parsing"
    - "Coalition structure handling"
    - "Interface compatibility"
    - "Basic import functionality"
  
  integration_tests:
    location: "tests/integration/"
    key_tests:
      - "Data loading validation"
      - "Coalition handling consistency" 
      - "Interface compatibility"
    exclude:
      - "Model training tests"  # Too slow for CI
      - "Performance benchmarks"  # Not needed for data prep

# Environment Configuration
environment:
  python_version: "3.11"
  package_manager: "pixi"
  environment_vars:
    PYTHONHASHSEED: "0"
    PYTHONUTF8: "1"
    OMP_NUM_THREADS: "2"
    NUMBA_NUM_THREADS: "2"

# Artifact Configuration  
artifacts:
  retention_days:
    test_results: 14
    pr_results: 7
  
  included_paths:
    - "test_results/"
    - "pr_test_results/"

# Security Configuration
security:
  permissions:
    contents: "read"
    pull_requests: "write"
    actions: "read"
  
  secrets_required:
    - "GITHUB_TOKEN"